# 共识参数
MAX_DELAY = 0.2  # 最大允许延迟(s)
VIEW_TIMEOUT = 2.0  # 视图超时时间(s)
BYZANTINE_TOLERANCE = 0.33  # 最大拜占庭节点比例

# 网络参数
QUEUE_LOAD_FACTOR = 100
MAX_QUEUE_SIZE = 500
NETWORK_DELAY_MEAN = 0.1
NETWORK_DELAY_STD = 0.03
PACKET_LOSS_RATE = 0.01

# 声誉参数
REPUTATION_DECAY = 0.85
MIN_REPUTATION = 0.65

# 仿真参数
SIMULATION_TICK = 0.01  # 10ms
TPS_DIVISOR = 100  # TPS缩放因子